// vue-project/003two-way-binding-and-computed/003SearchItems.vue
<script setup>
import {computed, reactive, ref} from 'vue';

const items = reactive(['svelte','vuejs','angular','react']);
const searchText = ref('');
const searchItems = computed(() => {
  return items
    .filter((item) => item.toUpperCase()
      .indexOf(searchText.value.toUpperCase()) !== -1
    );
});
</script>

<template>
  <div>
    <input type="text" v-model="searchText" />
    <ul>
      <li v-for="item in searchItems">{{ item }}</li>
    </ul>
  </div>
</template>

// react-project/003two-way-binding-and-computed/003SearchItems.jsx
import React, {useState} from 'react';

export function SearchItems(props) {
    const [searchText, setSearchText] = useState("");
    const items = ['svelte', 'vuejs', 'angular', 'react'];
    
    function handleSearchInput(event) {
        setSearchText(event.target.value);
    }
    
    return (
      <div>
          <input
            type="text"
            value={searchText}
            onChange={handleSearchInput}
          />
          <ul>
              {items.map((item) => (
                <li>{item}</li>
              ))}
          </ul>
      </div>
    );
}
